server:
  port: ${PORT:8003}

spring:
  application:
    name: kinetix-payment-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

midtrans:
  server-key: ${MIDTRANS_SERVER_KEY}
  client-key: ${MIDTRANS_CLIENT_KEY}
  is-production: ${MIDTRANS_IS_PRODUCTION:false}

grpc:
  server:
    port: ${GRPC_PORT:50056}
